// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class CameraPigeonCodecReader: FlutterStandardReader {
}

private class CameraPigeonCodecWriter: FlutterStandardWriter {
}

private class CameraPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CameraPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CameraPigeonCodecWriter(data: data)
  }
}

class CameraPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CameraPigeonCodec(readerWriter: CameraPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CameraApi {
  func switchCamera(completion: @escaping (Result<Void, Error>) -> Void)
  func takePicture(completion: @escaping (Result<Void, Error>) -> Void)
  func enableBeauty(completion: @escaping (Result<Void, Error>) -> Void)
  func disableBeauty(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CameraApiSetup {
  static var codec: FlutterStandardMessageCodec { CameraPigeonCodec.shared }
  /// Sets up an instance of `CameraApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CameraApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let switchCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.basic_beauty_cam.CameraApi.switchCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      switchCameraChannel.setMessageHandler { _, reply in
        api.switchCamera { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      switchCameraChannel.setMessageHandler(nil)
    }
    let takePictureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.basic_beauty_cam.CameraApi.takePicture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takePictureChannel.setMessageHandler { _, reply in
        api.takePicture { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      takePictureChannel.setMessageHandler(nil)
    }
    let enableBeautyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.basic_beauty_cam.CameraApi.enableBeauty\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enableBeautyChannel.setMessageHandler { _, reply in
        api.enableBeauty { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enableBeautyChannel.setMessageHandler(nil)
    }
    let disableBeautyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.example.basic_beauty_cam.CameraApi.disableBeauty\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disableBeautyChannel.setMessageHandler { _, reply in
        api.disableBeauty { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disableBeautyChannel.setMessageHandler(nil)
    }
  }
}
